### ISSUE TITLE
Assimp null checks when null values are possible

### ISSUE THREAD

**Issue by lenis0012** [LWJGL/lwjgl3#299]
The bindings for Assimp provide a method to release a scene import, and when it does, it checks to see if the pointers are not NULL.
Yet, when the scene does not contain, for instance, animations, the checks will fail and the application will crash.

I tried to manually free the used buffers and structs but that didn't work out too well, i'm assuming the memory got reallocated to something else.
I now call this method manually through the LWJGL JNI class like:
`JNI.invokePV(Functions.ReleaseImport, MemoryUtil.memAddressSafe(scene));`

and it seems to work nicely.

**Comment by Spasi** [comment]
The `AIScene` validation code checks the `mNum` members before checking the corresponding pointer. For example, `mAnimations` is checked only if `mNumAnimations` is not `0`. It does this for all members, they're all optional.

If the above doesn't help, please post a short code sample and the exception being thrown.

**Comment by lenis0012** [comment]
Unless i'm missing something
aiReleaseImport(AiScene) calls naiReleaseImport(long)
which then calls AiScene.validate(long)
in there each memory addressed is checked against NULL.
There is no reference to any num values.

This is the code in question:
https://gist.github.com/lenis0012/141ed69e8e58230de8d6e0658d83c17b

This is the program output:
`Animation count: 0
Exception in thread "main" java.lang.NullPointerException
	at org.lwjgl.system.Checks.check(Checks.java:94)
	at org.lwjgl.assimp.AIScene.validate(AIScene.java:439)
	at org.lwjgl.assimp.Assimp.naiReleaseImport(Assimp.java:2560)
	at org.lwjgl.assimp.Assimp.aiReleaseImport(Assimp.java:2572)
	at com.flipfire.arbor.engine.content.AssimpLoader.loadModel(AssimpLoader.java:61)
	at com.flipfire.arbor.ArborGame.initialize(ArborGame.java:42)
	at com.flipfire.arbor.engine.ArborEngine.run(ArborEngine.java:39)
	at com.flipfire.arbor.ArborGame.main(ArborGame.java:60)`

It throws the error after checking MANIMATIONS.

**Comment by Spasi** [comment]
Oh, you're on `3.1.1`. This bug has already been fixed with 6cb0b271f7c0dcdae97a2a49c5b753fab35644f8. The fix is available in `3.1.2` snapshots.

**Comment by lenis0012** [comment]
@Spasi Ah my bad.
I  actually looked the the changes to the bindings since december 2016, but I overlooked that commit.
So I thought it wasn't fixed.

I would be using the beta build if it were available for maven.
I guess ill just wait for the next stable release to replace the unsafe code in my project.
Thank you for your swift response.

**Comment by Spasi** [comment]
> I would be using the beta build if it were available for maven.

It is available via Sonatype's snapshots repository. See the generated script for Maven under Nightly in the [build configurator](https://www.lwjgl.org/download). Use `3.1.2-SNAPSHOT` as the LWJGL version and add this to your pom:

```xml
<repositories>
    <repository>
        <id>sonatype-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases><enabled>false</enabled></releases>
        <snapshots><enabled>true</enabled></snapshots>
    </repository>
</repositories>
```
